language: node_js
node_js:
  - "7"
script:
  - echo "Deploy!"
cache:
  paths:
    - $TRAVIS_BUILD_DIR/tals-site/node_modules/
install:
  - cd $TRAVIS_BUILD_DIR/tals-site
  - npm install
  - npm install -g firebase-tools
after_success:
  - cd $TRAVIS_BUILD_DIR/tals-site
  - cp -R $TRAVIS_BUILD_DIR/tals-site/node_modules/material-components-web/dist/*.min.* $TRAVIS_BUILD_DIR/tals-site/assets/
  - ls $TRAVIS_BUILD_DIR/tals-site/assets/
  - firebase deploy --project tals-app --token $FIREBASE_TOKEN