language: node_js
node_js:
  - "7"
script:
  - echo "Deploy!"
cache:
  paths:
    - $TRAVIS_BUILD_DIR/tals-site/node_modules/
install:
  - cd $TRAVIS_BUILD_DIR/tals-site
  - gem install slim
  - gem install sass
  - npm install -g firebase-tools
  - slimrb src/index.slim >| index.html
  - sass src/style.scss:assets/style.css 
after_success:
  - cd $TRAVIS_BUILD_DIR/tals-site
  - if [ "$TRAVIS_REPO_SLUG" == "thm-mni-ii/tals" ] && [ "$TRAVIS_BRANCH" == "master" ] && [ "$TRAVIS_PULL_REQUEST" == "false" ]; then
      firebase deploy --project tals-app --token $FIREBASE_TOKEN;
    fi